# Generated by Django 4.0.6 on 2022-07-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='egreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='FKDocumento', to='authApp.cliente'),
        ),
    ]
